// Algorithm to C++ generator
#ifndef __ABS_HEADER
#define __ABS_HEADER

#include <cmath> // TODO: Could be generated by IMPLEMENTATION <-- depends-on --> IMPLEMENTATION

class ABS {
	public:

		// Generate interface types
		typedef float RealNumber;

		// Generate function
		bool operator () (
			const RealNumber& x,
			RealNumber& y,
			void *ctx)
		{
			// Implement algorithm here
            y = std::abs(x);
			return true;
		}
};
#endif
